### This notebook is for tensorflow fundamentals.

In [1]:
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

# Checking tensorflow version

print(tf.__version__)

2.19.1


In [2]:
# Creating tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# checking the number of dimensions of a tensor.

scalar.ndim

# ndim stands for number of dimensions.

0

In [4]:
# creating a vector

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# checking dimensions of our vector

vector.ndim

1

In [6]:
# creating a matrix (that has more than 1 dimension)

matrix = tf.constant([[10,7], [7,10]])

matrix

# Note: by default tf.constant creates a tensor with dtype = int 32.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# checking dimensions of our matrix

matrix.ndim


2

In [8]:
# creating another matrix and this time we'll specify the datatype for our tensor.


matrix_2 = tf.constant([[10., 7.],
                        [3., 2.],
                        [8., 9.]], dtype = tf.float16)
matrix_2


# Shape = (3,2) specifies our tensor have 3 list with 2 values each.

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# checking dimensions of our matrix_2

matrix_2.ndim

2

In [10]:
# creating a tensor

tensor = tf.constant([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]], [[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
# checking dimensions of our tensor

tensor.ndim

3

## **Basics**

---

### 1. Matrix (singular)
A **matrix** is a single 2D array of numbers, arranged in rows and columns.  

Example:  

$A = \begin{bmatrix} 
1 & 2 \\ 
3 & 4 
\end{bmatrix}
$

### 2. Matrices (plural)
**Matrices** is simply the plural of **matrix**, meaning more than one.  

Example:  

$
A = \begin{bmatrix} 
1 & 2 \\ 
3 & 4 
\end{bmatrix}, \quad
B = \begin{bmatrix} 
5 & 6 \\ 
7 & 8 
\end{bmatrix}
$

Here, A and B together are **matrices**.


#### ✅ **Key Point**:  
- **Matrix** → one object.  
- **Matrices** → multiple objects.

---

### 3. Tensors 

A **matrix** is a special case of a **tensor**.

### Tensors by Rank
- **Scalar (just a number)** → Tensor of **rank 0** (No list).
- **Vector (1D array)** → Tensor of **rank 1** (A single list of elements).
- **Matrix (2D array)** → Tensor of **rank 2** (A list of two lists, with each inner list containing two elements.)
- **Higher-order Tensor (3D, 4D, ... N-D arrays)** → Tensor of **rank N**

### Key Idea
- Every **matrix is a tensor** (specifically, rank 2).
- But not every **tensor is a matrix** (since tensors can extend to more than 2 dimensions).

### Example
- Scalar: `5` → shape `()`
- Vector: `[1, 2, 3]` → shape `(3,)`
- Matrix: `[[1, 2],
          [3, 4]]`

### Are Matrices and Tensors the Same?

 - **No**

---

### Important Tensorflow functions

  - `tf.constant()` → creates a TensorFlow constant, which can represent a **scalar**, **vector**, **matrix**, or higher-order **tensor**, depending on the input.
  - `tf.ndim()` → returns the **rank** (number of dimensions) of the tensor.
  - `tf.shape()` → returns the **shape** (size along each dimension) of the tensor.

--- 

### Interpretation
> Shape of a scalar value is an empty list []
>
> Shape of a vector is given as [a], where "a" represents the number of elements in the list.
>
> Shape of a 2 dimensionsional matrix is given as [a, b], where "a" represents the number of lists inside the first list and "b" represents the number of elements inside each inner list.
>
> Shape of a tensor with dimension as 3 is given as [a, b, c], where "a" represents the number of lists inside the first list, "b" represents the number of lists inside each list that is present inside the first list and "c" represents the number of elements inside each list that is present inside a list which itself is inside the first list.

In [12]:
scalar.shape, vector.shape, matrix.shape, tensor.shape

(TensorShape([]),
 TensorShape([2]),
 TensorShape([2, 2]),
 TensorShape([3, 2, 3]))

In [13]:
# Creating tensor with tf.Variable

changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
unchangeable_tensor, changeable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

### Note: `tf.Variable` create tensors that are changeable while with `tf.constant` create tensors that are unchangable.

- To change the elements in our tensor we can't use assignment operator, Eg: `changeable_tensor[0] = 7` and this will throw an error. So to change elements in our tensor we use `.assign()`.
  
- **Note:** We can't change the element of a tensor created by `tf.constant` by using `unchangeable_tensor[0].assign(7)` because it'll throw an error.

In [14]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating random tensor (random tensors are tensors of some arbitrary size which contain random numbers)

## **Note:**
> `tf.random.Generator` creates a random tensor of arbitrary size.
>
>  `tf.normal()` fills the tensor with random values having a normal distribution.

In [15]:
# Creating two random (but the same) tensors

random_1 = tf.random.Generator.from_seed(42) # This is to get same results everytime we run our code.
random_1 = random_1.normal(shape = (3,2))

random_2 = tf.random.Generator.from_seed(42) # This is to get same results everytime we run our code.
random_2 = random_2.normal(shape = (3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### **Shuffle the order of elements in the Tensor**

- We shuffle the order of elements in the tensor, so that the performance of our model doesn't get affected by the order of inputs.
- **Example: Suppose we have a total of 15000 images for a classification problem. The first 10000 images are of class 1 while the other half is of class 2. So, if we don't shuffle our images, the input to our model for the early part will be biased towards class 1 and we want to nullify that and hence we use shuffling.** 

In [16]:
tensor_to_shuffle = tf.constant([[[10, 4], [7, 5]], [[3, 6], [4, 8]], [[2, 4], [5, 10]]])
tensor_to_shuffle

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[10,  4],
        [ 7,  5]],

       [[ 3,  6],
        [ 4,  8]],

       [[ 2,  4],
        [ 5, 10]]], dtype=int32)>

In [17]:
tensor_to_shuffle.ndim

# Dimensions are not concerned with th elements inside the list.
# Dimension: 1 = [], Dimension: 2 = [[]], Dimension: 3 = [[[]]]

3

In [18]:
tensor_to_shuffle.shape

TensorShape([3, 2, 2])

- The shape `[3, 2, 2]` describes a **3D tensor**.
- Breakdown:
  - `3` → There are **3 blocks** (outer lists).
  - `2` → Each block contains **2 rows** (inner lists).
  - `2` → Each row contains **2 elements**.

$[$

$[[10,  4], [ 7,  5]],$

$[[ 3,  6], [ 4,  8]],$

$[[ 2,  4], [ 5, 10]]$

$]$

### Note: `tf.random.shuffle` shuffles the tensor along it's first dimensions.

In [19]:
tf.random.shuffle(tensor_to_shuffle)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 3,  6],
        [ 4,  8]],

       [[10,  4],
        [ 7,  5]],

       [[ 2,  4],
        [ 5, 10]]], dtype=int32)>

### Why Use Operation-Level Seeds in TensorFlow?

TensorFlow supports **two levels of seeding** for random operations:

1. **Global seed** → Sets the overall randomness for the program.
2. **Operation-level seed** → Sets randomness for a specific operation (e.g., `tf.random.uniform`, `tf.random.normal`).

---

#### Why operation-level seed alone is not deterministic
- If you set **only the op-level seed**, TensorFlow still mixes it with the global random state.  
- This means results may differ between runs, even if the same op-level seed is used.

---

#### Why it is useful
- ✅ **Reproducibility (with global seed):**  
  When **both global seed and op-level seed** are set, the operation produces the same result every run.  
- ✅ **Independent control:**  
  Different operations can be assigned different seeds so they don’t produce identical random sequences.  
- ✅ **Debugging / Experiment tracking:**  
  Lets you control randomness for a specific operation without affecting others.

---

**Key Point:**  
- *Op-level seed alone ≠ deterministic*  
- *Global seed + op-level seed = reproducible results*


In [20]:
# Global level seed
tf.random.set_seed(1234)

print(tf.random.uniform([1]))  # generates 0.5380393
print(tf.random.uniform([1]))  # generates 0.3253647

# re-run the code to check change.

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [21]:
# operations level seed
print(tf.random.uniform([1], seed = 4321))  
print(tf.random.uniform([1], seed = 4321)) 

# re-run the code to check change.

tf.Tensor([0.46764243], shape=(1,), dtype=float32)
tf.Tensor([0.15858293], shape=(1,), dtype=float32)


In [22]:
# Global level seed and operations level seed

tf.random.set_seed(1234)

print(tf.random.uniform([1], seed = 4321)) # 0.46764243
print(tf.random.uniform([1], seed = 4321)) # 0.15858293 

# re-run the code to check change.

tf.Tensor([0.46764243], shape=(1,), dtype=float32)
tf.Tensor([0.15858293], shape=(1,), dtype=float32)


## Creating a tensor of all zeroes and ones.

In [23]:
tf.zeros(shape = (3, 4)) # all zeroes

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [24]:
tf.ones(shape = (3,4)) # all ones

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

## Note: We can also turn numpy arrays into tensors.

- The main difference between Numpy arrays and tensors in tensorflow is that tensors can be run on a GPU for faster numerical computation.

In [25]:
array = np.arange(1,25, dtype = np.int32) # creating a numpy array between 1 and 25.
array # An array is an indexed collection of elements of the same data type, arranged in one or more dimensions.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [26]:
tensor = tf.constant(array)
tensor # tensor from a numpy array.

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [27]:
# We can also change the shape of the tensor as,

tensor_1 = tf.constant(array, shape = (2,3,4))
tensor_1

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### **Note:** We use shape = (2,3,4) because 2*3*4 = 24 and the original numpy array had 24 elements. So, we can choose a shape from only the factors of 24.
---

### Getting information from tensors or the information that is important related to tensors.

- Shape
- Rank
- Axis or dimension
- Size

In [28]:
# Creating a rank 4 tensor

tensor_rank_4 = tf.zeros(shape= (2, 3, 4, 5))

tensor_rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
tensor_rank_4.dtype, tensor_rank_4.shape, tensor_rank_4.ndim, tf.size(tensor_rank_4)

# ndim gives number of dimensions or rank.

(tf.float32,
 TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### `tf.size()` is used to get the total number of elements inside the tensor. However, the output it produces contains extra information as shown in the previous cell. So, if we want to get just the number of elements we can use `tf.size().numpy()`

In [30]:
tf.size(tensor_rank_4).numpy()

np.int32(120)

## Indexing Tensors

- Tensors can be indexed just like Python lists.

In [31]:
## In python we can get the elements of any list as

somelist = [1, 2, 3, 4, 5, 6 ]

a = somelist[:3]
## This will give us first three elements of our list.

b = somelist[3:]
## This will be give us all the elements of our list after the 3rd element.

c = somelist[2:6]
## This will be give us all the elements of our list after the 2nd element till the 6th element.

a, b, c

([1, 2, 3], [4, 5, 6], [3, 4, 5, 6])

In [32]:
# Getting the first 2 element of each dimension.

tensor_rank_4[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

- tensor_rank_4 is a tensor with shape = (2,3,4,5).
    
- tensor_rank_4[:2, :2, :2, :2] gave us a tensor of shape (2,2,2,2) because it is selecting 2 elements from each list.

In [33]:
## Getting the first element from each dimension except the final one.

tensor_rank_4[:1, :1, :1, :] # This works the same as "tensor_rank_4[:1, :1, :1]"

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

### Note: The shape is (1, 1, 1, 5) because the last dimension was selected as a whole.

In [34]:
rank_d = tf.constant([
                       [ # outer block 1
                           [1,2,3], # inner block 1
                           [4,5,6] # inner block 2
                       ],
                      
                       [ # outer block 2
                           [7,8,9], # inner block 1
                           [1,4,7] # inner block 2
                       ]
                    ])

rank_d, rank_d.shape, rank_d.ndim

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[7, 8, 9],
         [1, 4, 7]]], dtype=int32)>,
 TensorShape([2, 2, 3]),
 3)

In [35]:
rank_d[:,:,-1]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 6],
       [9, 7]], dtype=int32)>

### Breakdown

- Select all outer blocks.
- Select all inner blocks (lists) in each outer block.
- Select only the last element in each inner block.

---

# Manipulating Tensors

---

### Adding extra dimension to an tensor. 

- Example: Converting a rank 2 tensor into rank 3 tensor.
- In tensorflow, `tf.newaxis` and  `tf.expand_dims` are the methods that are available to extend dimensions of a tensor.

### Method1: `tf.newaxis`

In [36]:
rank_2 = tf.constant([[10,7], [3,4]]) # example

In [37]:
rank_3 = rank_2[..., tf.newaxis] # "..." means keep every other axis as same as before.
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [38]:
rank_3.ndim, rank_3.shape

(3, TensorShape([2, 2, 1]))

### Method2: `tf.expand_dims` is an alternative to `tf.newaxis`.

- #### It can be used to expand the first or the last axis of a tensor.

In [39]:
tf.expand_dims(rank_2, axis = 0) # expanding first axis.

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [40]:
tf.expand_dims(rank_2, axis = -1) # expanding last axis.

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [41]:
## we can also use, tf.newaxis as

rank_3 = rank_2[:, :, tf.newaxis]
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### 2) Altering values of a tensor using normal mathmatical operators including, addition, multiplication, subtraction, and others.

In [42]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [43]:
tensor ## Original tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [44]:
tensor*10 ## multiplication also works

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [45]:
tensor - 10 ## Subtraction

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [46]:
tf.multiply(tensor, 10) ## For such operations, we can also use tensorflow built-in functions as

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

## **Matrix Multiplication**

In [47]:
a = tf.constant([[10, 7], [3, 4]])
b = tf.constant([[3, 4], [10, 7]])
a * b # Note: a * b doesn't perform matrix multiplication. It just multiplies the matrix element-vise.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 28],
       [30, 28]], dtype=int32)>

In [48]:
# To perform matrix multiplication we can use
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  89],
       [ 49,  40]], dtype=int32)>

In [49]:
## In base python without tensorflow, we can use "@" to perform matrix multiplication

a@b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  89],
       [ 49,  40]], dtype=int32)>

In [50]:
# Note: Matrix can be multiplied only when the no of columns in the first matrix is equal to the number of rows in the second matrix.

A = tf.constant([[10, 7],
                 [3, 4],
                 [9, 5]])

B = tf.constant([[10, 7],
                 [3, 4],
                 [9, 5]])


# Here, A@B will throw an error because the number of rows in A is not equal to number of columns in B, their multiplication is not possible.
# hence, "tf.matmul(A, B)" will also throw an error.

# To overcome this issue, we can can reshape B.
# Generally, taking transpose is preferred over using tf.reshape()

n_B = tf.reshape(B, shape =(2,3)) ## Reshaping B

# Now we can multiply our matrix

A, n_B, A @ n_B

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 9,  5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  7,  3],
        [ 4,  9,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[128, 133,  65],
        [ 46,  57,  29],
        [110, 108,  52]], dtype=int32)>)

In [51]:
# We can also perform the matrix multiplication by taking the transpose as

C = tf.transpose(B)

A, B, C, A@C

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 9,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 9,  5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  3,  9],
        [ 7,  4,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[149,  58, 125],
        [ 58,  25,  47],
        [125,  47, 106]], dtype=int32)>)

## Matrix multiplication is also referred as `dot product`.

- We can perform matrix multiplication by using
  
> #### `tf.matmul()`
>
> #### `tf.tensordot()`
>
> #### `@`

In [52]:
# Performing dot product on A and B

tf.tensordot(A, tf.transpose(B), axes = 1) # "axes = 1" peroforms normal matrix multiplication.

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[149,  58, 125],
       [ 58,  25,  47],
       [125,  47, 106]], dtype=int32)>

In [53]:
tf.matmul(A, tf.transpose(B))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[149,  58, 125],
       [ 58,  25,  47],
       [125,  47, 106]], dtype=int32)>

## Changing the datatype of a tensor

In [54]:
f = tf.constant([10, 7, 8])
f.dtype

# The default datatype of the tensor with integers as it's element is int32.

tf.int32

In [55]:
g = tf.constant([10.0, 7.9, 8.6])
g.dtype

# The default datatype of the tensor with floating point numbers as it's element is float32.

tf.float32

In [56]:
# Changing datatype from float32 to float16 (and this is referred as reduced precision)

h = tf.cast(g, dtype = tf.float16)
h.dtype

tf.float16

In [57]:
# changing from int32 to float32

i = tf.cast(f, dtype = tf.float32)
i, i.dtype

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([10.,  7.,  8.], dtype=float32)>,
 tf.float32)

# Aggregating Tensors

**Aggregation** means combining or summarizing values into a single result (or a smaller set of results). 

> In TensorFlow, we often aggregate tensors to extract meaningful statistics.

---

## Common Forms of Aggregation

- **Absolute value (`tf.abs`)**  
  Converts all elements to their non-negative values.  

- **Minimum (`tf.reduce_min`)**  
  Finds the smallest element in the tensor.  

- **Maximum (`tf.reduce_max`)**  
  Finds the largest element in the tensor.  

- **Mean (`tf.reduce_mean`)**  
  Computes the average value of all elements.  

- **Sum (`tf.reduce_sum`)**  
  Adds up all the elements of the tensor.  


In [58]:
xz = tf.constant([-10,-7])
xz

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-10,  -7], dtype=int32)>

In [59]:
tf.abs(xz) # Getting the absolute value.

### tf.abs() converts all the -ve values in a tensor into +ve values.

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [60]:
xy = tf.constant(np.random.randint(0, 100, size = 50)) # creating a random tensor
xy

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([44, 94, 72, 11, 30, 76, 81, 32, 10, 58, 86, 71,  8, 12, 23, 30,  6,
       45, 62, 13, 18, 81, 83, 38, 66, 77, 73, 33, 97, 46, 92, 89, 87, 71,
       18, 81, 73, 78, 81, 26, 77, 66, 75, 95, 41, 20, 88,  4, 83, 84])>

In [61]:
tf.reduce_min(xy) # getting minimum of a tensor.

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [62]:
tf.reduce_max(xy) # getting maximum of a tensor.

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [63]:
tf.reduce_mean(xy) # getting mean of a tensor.

<tf.Tensor: shape=(), dtype=int64, numpy=56>

In [64]:
tf.reduce_sum(xy) # getting sum of a tensor.

<tf.Tensor: shape=(), dtype=int64, numpy=2805>

## Variance of a Tensor

Variance is calculated by finding the mean, subtracting it from each value, squaring the differences, and then averaging those squared differences.

### How Variance is Calculated

1. **Find the mean** of all numbers.  
   $\mu = \frac{\sum x_i}{N}$

2. **Calculate the difference** of each number from the mean.  
   $x_i - \mu$

3. **Square each difference** to remove negatives.  
   $(x_i - \mu)^2$

4. **Take the average of these squared differences**.  
   $\text{Variance} = \frac{\sum (x_i - \mu)^2}{N}$

---

- #### Variance of a tensor is a measure of how far its elements are spread out from its mean.
- #### In TensorFlow, variance is not available directly in `tf.*`, but we can use the **TensorFlow Probability** module.
- #### `tfp.stats.variance(tensor_name)` from **tensorflow_probability**.

In [65]:
tfp.stats.variance(xy) # Using getting variance of a tensor.

<tf.Tensor: shape=(), dtype=int64, numpy=865>

In [66]:
# Another way of finding variance

tf.math.reduce_variance(tf.cast(xy, dtype = tf.float32))

## This is done because "tf.math.reduce_variance" don't take integer values as input, so we convert data type into float32.

<tf.Tensor: shape=(), dtype=float32, numpy=865.72998046875>

In [67]:
## Standard deviation is the square root of variance.


tf.math.reduce_std(tf.cast(xy, dtype = tf.float32)), tf.math.reduce_variance(tf.cast(xy, dtype = tf.float32))**0.5

## Again "tf.math.reduce_std()" don't take integer values as input, hence, we cast its dtype into float32.

(<tf.Tensor: shape=(), dtype=float32, numpy=29.423290252685547>,
 <tf.Tensor: shape=(), dtype=float32, numpy=29.423290252685547>)

## Finding Positional Maximum and Minimum of a tensor.

In [68]:
# Creating a new tensor for demonstration.

tf.random.set_seed(42)

gh = tf.random.uniform(shape = [50]) # this creates a tensor with 50 elements all between 0 & 1 having uniform distribution.
gh

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [69]:
tf.argmin(input = gh), gh[tf.argmin(input = gh)]

## So, the index of minimum value is 16 while the minimum value is 0.009463668

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>)

In [70]:
tf.argmax(input = gh), gh[tf.argmax(input = gh)]

## So, the index of maximum value is 42 while the maximum value is 0.9671384

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>)

## Squeezing a tensor(removing all single dimension)

In [71]:
tf.random.set_seed(42)
kh = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1,50))
kh

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [72]:
kh.shape

TensorShape([1, 1, 1, 1, 50])

In [73]:
kh_squeezed = tf.squeeze(kh)  # So, "tf.squeeze()" removes all the single dimensions.
kh_squeezed, kh_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

# One-Hot Encoding in TensorFlow

### What is One-Hot Encoding?
- **One-hot encoding** is a method to represent categorical data (e.g., labels or classes) as binary vectors.  
- Each category is converted into a vector where:
  - The index corresponding to the category is marked as `1`.
  - All other positions are `0`.

---

### Example
Suppose we have 3 classes: `{0, 1, 2, 3}`. This could be interpreted as red, green, blue, purple.

- Red `0` → `[1, 0, 0, 0]`  
- Green `1` → `[0, 1, 0, 0]`  
- Blue `2` → `[0, 0, 1, 0]`  
- Purple `3` → `[0, 0, 0, 1]`

It is just like a taffic signal, where we can have red, green and orange light but at a certain point only 1 of them can glow while the others don't. So each label is represented by a vector of length equal to the **number of classes**.

In [74]:
some_list = [0, 1, 2, 3] # Creating a list of indices.
depth = 4
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [75]:
## Instead of 0 and 1 we can also specify other values as

tf.one_hot(some_list, depth =4, on_value = "hello", off_value = "bye")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'hello', b'bye', b'bye', b'bye'],
       [b'bye', b'hello', b'bye', b'bye'],
       [b'bye', b'bye', b'hello', b'bye'],
       [b'bye', b'bye', b'bye', b'hello']], dtype=object)>

## Other operations on a tensor
- #### Squaring
- #### log
- #### square root

In [76]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [77]:
tf.square(H) # Square

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [78]:
tf.sqrt(tf.cast(H, dtype = tf.float32)) # Square root

# Note: "tf.sqrt()" don't take integer values as input.

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [79]:
tf.math.log(tf.cast(H, dtype = tf.float32)) # Log

# Note: "tf.math.log()" don't take integer values as input.

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [80]:
xy, tf.sort(xy,direction='DESCENDING') # Sorting a list with tensor flow.

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([44, 94, 72, 11, 30, 76, 81, 32, 10, 58, 86, 71,  8, 12, 23, 30,  6,
        45, 62, 13, 18, 81, 83, 38, 66, 77, 73, 33, 97, 46, 92, 89, 87, 71,
        18, 81, 73, 78, 81, 26, 77, 66, 75, 95, 41, 20, 88,  4, 83, 84])>,
 <tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([97, 95, 94, 92, 89, 88, 87, 86, 84, 83, 83, 81, 81, 81, 81, 78, 77,
        77, 76, 75, 73, 73, 72, 71, 71, 66, 66, 62, 58, 46, 45, 44, 41, 38,
        33, 32, 30, 30, 26, 23, 20, 18, 18, 13, 12, 11, 10,  8,  6,  4])>)

## Tensors and Numpy
- #### Tensorflow interacts very well with Numpyarrays.

In [81]:
J = tf.constant(np.array([3.1 ,7.1 , 10.1])) ## Creating a tensor from a Numpy array.
J, type(J)

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.1,  7.1, 10.1])>,
 tensorflow.python.framework.ops.EagerTensor)

In [82]:
np.array(J), type(np.array(J)) ## converting our tensor back to numpy array.

(array([ 3.1,  7.1, 10.1]), numpy.ndarray)

In [83]:
J.numpy(), type(J.numpy()) ## Another way of converting a tensor into a numpy array.

(array([ 3.1,  7.1, 10.1]), numpy.ndarray)

In [84]:
# The default data type of each are slightly different and it is shown as

numpy_J = tf.constant(np.array([3., 7., 9.]))
tensor_J = tf.constant([3., 7., 9.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

- #### Although both are tensors with same shape and elements but still they have different data type.
- #### The major difference between tensorflow tensor and numpy array is that tensorflow tensor can be run on GPU or TPU for faster numerical computing.

### In base python without tensorflow, we can use "@" to perform matrix multiplication as

- #### matrix_a@matrix_b

---

### We can also create our own fnction to perform matrix multiplication.

In [85]:
def matmul(A, B):
    # Get dimensions
    rows_A, cols_A = len(A), len(A[0])
    rows_B, cols_B = len(B), len(B[0])
    
    # Check if multiplication is possible
    if cols_A != rows_B:
        raise ValueError("Number of columns of A must equal number of rows of B")
    
    # Initialize result with zeros
    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]
    
    # Multiply
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):  # or rows_B, since cols_A == rows_B
                result[i][j] += A[i][k] * B[k][j]
    
    return result

In [86]:
A = np.array([[10, 7], [3, 4]])
B = np.array([[3, 4], [10, 7]])

matmul(A, B)

[[np.int64(100), np.int64(89)], [np.int64(49), np.int64(40)]]

In [87]:
A@B

array([[100,  89],
       [ 49,  40]])